site_name: Baltimore Black Techies present 100 Days of Code
site_description: 100 days of code progress
site_author: Baltimore Black Techies
repo_url: https://github.com/baltimoreblacktechies/100daysOfCode-2021
theme:
  name: material
  logo: 'https://avatars.githubusercontent.com/u/44561649?s=200&v=4'
  favicon: 'https://avatars.githubusercontent.com/u/44561649?s=200&v=4'
  palette:
    primary: 'white'

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - codehilite:
      linenums: true

extra_javascript: [
  'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML',
  'https://unpkg.com/@hpcc-js/wasm@0.3.11/dist/index.min.js']

nav:
  - Home:
    - index.md
  - Progress:
